### PR TITLE
Request tracing

### PR DESCRIPTION
**Pull request by wheresrhys**
@Financial-Times/next-myft @matthew-andrews 

Not sure if my use of makefile is optimal

### CODE REVIEW

**Comment by matthew-andrews** [comment]
makefile looks optimal

**Comment by phamann** [comment]
I assume you've commented out the new `nbt verify` due to the new stricter rules?

**Comment by phamann** [comment]
Did you mean to commit changes to `jobs/_synchronize-concepts-local.js`

**Comment by wheresrhys** [comment]
yes, otherwise fails linting. Those functions are not referenced anywhere

**Comment by wheresrhys** [comment]
don't know why failing. Taking the easy way out

**Pull request closed without merging**
